"""empty message

Revision ID: 0ac31f8e4338
Revises: 08343b4eee0a
Create Date: 2019-07-17 14:07:35.827615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac31f8e4338'
down_revision = '08343b4eee0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membernewspost') as batch_op:  
      batch_op.drop_column('is_announcement')
    # op.create_index(op.f('ix_user_userAccess'), 'user', ['userAccess'], unique=False)
    # op.drop_index('ix_user_userAccess', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_user_userAccess', 'user', ['userAccess'], unique=False)
    # op.drop_index(op.f('ix_user_userAccess'), table_name='user')
    op.add_column('membernewspost', sa.Column('is_announcement', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
