"""added user to news post

Revision ID: 22ce75ac8c36
Revises: e5a30a46da02
Create Date: 2019-04-01 14:28:04.738515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ce75ac8c36'
down_revision = 'e5a30a46da02'
branch_labels = None
depends_on = None


def upgrade():
  pass
    # ### commands auto generated by Alembic - please adjust! ###
    
    #op.add_column('membernewspost', sa.Column('user', sa.String(), nullable=False))
    # op.create_index(op.f('ix_user_userAccess'), 'user', ['userAccess'], unique=False)
    # op.drop_index('ix_user_userAccess', table_name='user')
    # ### end Alembic commands ###


def downgrade():
  pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_user_userAccess', 'user', ['userAccess'], unique=False)
    # op.drop_index(op.f('ix_user_userAccess'), table_name='user')
    #op.drop_column('membernewspost', 'user')
    # ### end Alembic commands ###
