"""remove user

Revision ID: 2aa82f725608
Revises: 22ce75ac8c36
Create Date: 2019-04-01 15:07:50.864487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa82f725608'
down_revision = '22ce75ac8c36'
branch_labels = None
depends_on = None


def upgrade():
  pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_user_userAccess'), 'user', ['userAccess'], unique=False)
     #op.drop_index('ix_user_userAccess', table_name='user')
    # ### end Alembic commands ###


def downgrade():
  pass
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('ix_user_userAccess', 'user', ['userAccess'], unique=False)
    #op.drop_index(op.f('ix_user_userAccess'), table_name='user')
    # ### end Alembic commands ###
