"""added is_announcement field with default

Revision ID: 33cb9a7b62d7
Revises: cfe548f71ad8
Create Date: 2019-07-16 13:56:19.216245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33cb9a7b62d7'
down_revision = 'cfe548f71ad8'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute()
    # op.alter_column('membernewspost', 'is_announcement',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            server_default='false')
    # op.create_index(op.f('ix_user_userAccess'), 'user', ['userAccess'], unique=False)
    # op.drop_index('ix_user_userAccess', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_user_userAccess', 'user', ['userAccess'], unique=False)
    # op.drop_index(op.f('ix_user_userAccess'), table_name='user')
    # op.alter_column('membernewspost', 'is_announcement',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True)
    # ### end Alembic commands ###
