"""add user 2

Revision ID: 420cc3f341d7
Revises: ab8744af7034
Create Date: 2019-04-04 13:58:54.252325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420cc3f341d7'
down_revision = 'ab8744af7034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_userAccess'), 'user', ['userAccess'], unique=False)
    op.drop_index('ix_user_userAccess', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_userAccess', 'user', ['userAccess'], unique=False)
    op.drop_index(op.f('ix_user_userAccess'), table_name='user')
    # ### end Alembic commands ###
