"""add about column

Revision ID: 43dbc7ea3996
Revises: 7666ca122db1
Create Date: 2018-12-27 13:55:52.452445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43dbc7ea3996'
down_revision = '7666ca122db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about', sa.String(), nullable=True))
    #op.create_index(op.f('ix_user_userAccess'), 'user', ['userAccess'], unique=False)
    #op.drop_index('ix_user_userAccess', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_userAccess', 'user', ['userAccess'], unique=False)
    op.drop_index(op.f('ix_user_userAccess'), table_name='user')
    op.drop_column('user', 'about')
    # ### end Alembic commands ###
