"""added more user info

Revision ID: 7666ca122db1
Revises: 91eba7163034
Create Date: 2018-09-24 14:19:35.719005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7666ca122db1'
down_revision = '91eba7163034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('elPage', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('twitch', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('twitter', sa.String(length=256), nullable=True))
    #op.create_index(op.f('ix_user_userAccess'), 'user', ['userAccess'], unique=False)
    #op.drop_index('ix_user_userAccess', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('ix_user_userAccess', 'user', ['userAccess'], unique=False)
    #op.drop_index(op.f('ix_user_userAccess'), table_name='user')
    op.drop_column('user', 'twitter')
    op.drop_column('user', 'twitch')
    op.drop_column('user', 'elPage')
    # ### end Alembic commands ###
