"""remove stuff

Revision ID: cf2e81a7d960
Revises: 33cb9a7b62d7
Create Date: 2019-07-16 14:35:07.538999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf2e81a7d960'
down_revision = '33cb9a7b62d7'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('membernewspost', 'is_announcement',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # op.create_index(op.f('ix_user_userAccess'), 'user', ['userAccess'], unique=False)
    # op.drop_index('ix_user_userAccess', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_user_userAccess', 'user', ['userAccess'], unique=False)
    # op.drop_index(op.f('ix_user_userAccess'), table_name='user')
    # op.alter_column('membernewspost', 'is_announcement',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True)
    # ### end Alembic commands ###
