"""added is_announcement field

Revision ID: cfe548f71ad8
Revises: 420cc3f341d7
Create Date: 2019-07-16 13:52:05.027522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe548f71ad8'
down_revision = '420cc3f341d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membernewspost', sa.Column('is_announcement', sa.Boolean()))
    # op.create_index(op.f('ix_user_userAccess'), 'user', ['userAccess'], unique=False)
    # op.drop_index('ix_user_userAccess', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_user_userAccess', 'user', ['userAccess'], unique=False)
    # op.drop_index(op.f('ix_user_userAccess'), table_name='user')
    op.drop_column('membernewspost', 'is_announcement')
    # ### end Alembic commands ###
